COL_multi_gabor_staircase = [
    "blocks.thisN",
    "blocks.thisIndex",
    "trials.label",
    "trials.eccentricity",
    "trials.garbor_size_in_deg",
    "trials.setsize",
    "trials.sf_in_cycle_per_deg",
    "trials.ref_ori",
    "trials.thisN",
    "trials.direction",
    "trials.intensity",
    "trials.response",
    "participant",
    "age",
    "sex"]
